import { DeviceMetadata, deviceMetadataSchema } from "@/types/device-metadata"
import { Keycode } from "@/types/keycodes"

export const GAUSS64: DeviceMetadata = deviceMetadataSchema.parse({
  name: "GAUSS64",
  vendorId: 0xab50,
  productId: 0xab01,
  numKeys: 64,
  numAKC: 32,
  layout: [
    [
      { key: 0, w: 1.5, h: 1, x: 0, y: 0 },
      { key: 1, w: 1, h: 1, x: 0, y: 0 },
      { key: 2, w: 1, h: 1, x: 0, y: 0 },
      { key: 3, w: 1, h: 1, x: 0, y: 0 },
      { key: 4, w: 1, h: 1, x: 0, y: 0 },
      { key: 5, w: 1, h: 1, x: 0, y: 0 },
      { key: 6, w: 1, h: 1, x: 0, y: 0 },
      { key: 7, w: 1, h: 1, x: 0, y: 0 },
      { key: 8, w: 1, h: 1, x: 0, y: 0 },
      { key: 9, w: 1, h: 1, x: 0, y: 0 },
      { key: 10, w: 1, h: 1, x: 0, y: 0 },
      { key: 11, w: 1, h: 1, x: 0, y: 0 },
      { key: 12, w: 1, h: 1, x: 0, y: 0 },
      { key: 13, w: 1.5, h: 1, x: 0, y: 0 },
    ],
    [
      { key: 14, w: 1.5, h: 1, x: 0, y: 0 },
      { key: 15, w: 1, h: 1, x: 0, y: 0 },
      { key: 16, w: 1, h: 1, x: 0, y: 0 },
      { key: 17, w: 1, h: 1, x: 0, y: 0 },
      { key: 18, w: 1, h: 1, x: 0, y: 0 },
      { key: 19, w: 1, h: 1, x: 0, y: 0 },
      { key: 20, w: 1, h: 1, x: 0, y: 0 },
      { key: 21, w: 1, h: 1, x: 0, y: 0 },
      { key: 22, w: 1, h: 1, x: 0, y: 0 },
      { key: 23, w: 1, h: 1, x: 0, y: 0 },
      { key: 24, w: 1, h: 1, x: 0, y: 0 },
      { key: 25, w: 1, h: 1, x: 0, y: 0 },
      { key: 26, w: 1, h: 1, x: 0, y: 0 },
      { key: 27, w: 1.5, h: 1, x: 0, y: 0 },
    ],
    [
      { key: 28, w: 1.5, h: 1, x: 0, y: 0 },
      { key: 29, w: 1, h: 1, x: 0, y: 0 },
      { key: 30, w: 1, h: 1, x: 0, y: 0 },
      { key: 31, w: 1, h: 1, x: 0, y: 0 },
      { key: 32, w: 1, h: 1, x: 0, y: 0 },
      { key: 33, w: 1, h: 1, x: 0, y: 0 },
      { key: 34, w: 1, h: 1, x: 0, y: 0 },
      { key: 35, w: 1, h: 1, x: 0, y: 0 },
      { key: 36, w: 1, h: 1, x: 0, y: 0 },
      { key: 37, w: 1, h: 1, x: 0, y: 0 },
      { key: 38, w: 1, h: 1, x: 0, y: 0 },
      { key: 39, w: 1, h: 1, x: 0, y: 0 },
      { key: 40, w: 1.5, h: 1, x: 0, y: 0 },
      { key: 41, w: 1, h: 1, x: 0, y: 0 },
    ],
    [
      { key: 42, w: 1.5, h: 1, x: 0, y: 0 },
      { key: 43, w: 1, h: 1, x: 0, y: 0 },
      { key: 44, w: 1, h: 1, x: 0, y: 0 },
      { key: 45, w: 1, h: 1, x: 0, y: 0 },
      { key: 46, w: 1, h: 1, x: 0, y: 0 },
      { key: 47, w: 1, h: 1, x: 0, y: 0 },
      { key: 48, w: 1, h: 1, x: 0, y: 0 },
      { key: 49, w: 1, h: 1, x: 0, y: 0 },
      { key: 50, w: 1, h: 1, x: 0, y: 0 },
      { key: 51, w: 1, h: 1, x: 0, y: 0 },
      { key: 52, w: 1, h: 1, x: 0, y: 0 },
      { key: 53, w: 1.5, h: 1, x: 0, y: 0 },
      { key: 54, w: 1, h: 1, x: 0, y: 0 },
      { key: 55, w: 1, h: 1, x: 0, y: 0 },
    ],
    [
      { key: 56, w: 1.5, h: 1, x: 0, y: 0 },
      { key: 57, w: 1, h: 1, x: 0, y: 0 },
      { key: 58, w: 1.5, h: 1, x: 0, y: 0 },
      { key: 59, w: 7, h: 1, x: 0, y: 0 },
      { key: 60, w: 1, h: 1, x: 0, y: 0 },
      { key: 61, w: 1, h: 1, x: 0, y: 0 },
      { key: 62, w: 1, h: 1, x: 0, y: 0 },
      { key: 63, w: 1, h: 1, x: 0, y: 0 },
    ],
  ],
  defaultKeymap: [
    [
      Keycode.KC_ESC,
      Keycode.KC_1,
      Keycode.KC_2,
      Keycode.KC_3,
      Keycode.KC_4,
      Keycode.KC_5,
      Keycode.KC_6,
      Keycode.KC_7,
      Keycode.KC_8,
      Keycode.KC_9,
      Keycode.KC_0,
      Keycode.KC_MINS,
      Keycode.KC_EQL,
      Keycode.KC_BSPC, // Row 1
      Keycode.KC_TAB,
      Keycode.KC_Q,
      Keycode.KC_W,
      Keycode.KC_E,
      Keycode.KC_R,
      Keycode.KC_T,
      Keycode.KC_Y,
      Keycode.KC_U,
      Keycode.KC_I,
      Keycode.KC_O,
      Keycode.KC_P,
      Keycode.KC_LBRC,
      Keycode.KC_RBRC,
      Keycode.KC_BSLS, // Row 2
      Keycode.KC_CAPS,
      Keycode.KC_A,
      Keycode.KC_S,
      Keycode.KC_D,
      Keycode.KC_F,
      Keycode.KC_G,
      Keycode.KC_H,
      Keycode.KC_J,
      Keycode.KC_K,
      Keycode.KC_L,
      Keycode.KC_SCLN,
      Keycode.KC_QUOT,
      Keycode.KC_ENT,
      Keycode.KC_NO, // Row 3
      Keycode.KC_LSFT,
      Keycode.KC_Z,
      Keycode.KC_X,
      Keycode.KC_C,
      Keycode.KC_V,
      Keycode.KC_B,
      Keycode.KC_N,
      Keycode.KC_M,
      Keycode.KC_COMM,
      Keycode.KC_DOT,
      Keycode.KC_SLSH,
      Keycode.KC_RSFT,
      Keycode.KC_UP,
      Keycode.KC_LAYER_1, // Row 4
      Keycode.KC_LCTL,
      Keycode.KC_LGUI,
      Keycode.KC_LALT,
      Keycode.KC_SPC,
      Keycode.KC_RALT,
      Keycode.KC_LEFT,
      Keycode.KC_DOWN,
      Keycode.KC_RGHT, // Row 5
    ],
    [
      Keycode.KC_GRV,
      Keycode.KC_F1,
      Keycode.KC_F2,
      Keycode.KC_F3,
      Keycode.KC_F4,
      Keycode.KC_F5,
      Keycode.KC_F6,
      Keycode.KC_F7,
      Keycode.KC_F8,
      Keycode.KC_F9,
      Keycode.KC_F10,
      Keycode.KC_F11,
      Keycode.KC_F12,
      Keycode.KC_DEL, // Row 1
      Keycode.KC_PSCR,
      Keycode._______,
      Keycode.KC_PGUP,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode.KC_PF0,
      Keycode.KC_PF1,
      Keycode.KC_PF2,
      Keycode.KC_PF3,
      Keycode._______, // Row 2
      Keycode._______,
      Keycode.KC_HOME,
      Keycode.KC_PGDN,
      Keycode.KC_END,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode.KC_MPRV,
      Keycode.KC_MPLY,
      Keycode.KC_MNXT,
      Keycode._______,
      Keycode._______,
      Keycode.KC_PSWP,
      Keycode._______, // Row 3
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode.KC_MUTE,
      Keycode.KC_VOLD,
      Keycode.KC_VOLU,
      Keycode._______,
      Keycode._______,
      Keycode._______, // Row 4
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______,
      Keycode._______, // Row 5
    ],
    Array(64).fill(Keycode._______),
    Array(64).fill(Keycode._______),
  ],
})
