/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ChevronsDownIcon,
} from "lucide-react"

import { KeycodeMetadata } from "@/types/keycodes"
import { Keycode } from "@/types/libhmk/keycodes"

export const EXTENDED_KEYCODE_METADATA: KeycodeMetadata[] = [
  {
    name: "",
    tooltip: "No Binding",
    keycode: Keycode.KC_NO,
    webCodes: [],
    category: "Extended",
  },
  {
    name: "Transparent",
    tooltip:
      "Transparent Key. Fallback to the highest active layer with a non-transparent key.",
    display: [ChevronsDownIcon],
    keycode: Keycode.KC_TRANSPARENT,
    webCodes: [],
    category: "Extended",
  },
  {
    name: "Enter",
    keycode: Keycode.KC_ENTER,
    webCodes: ["Enter"],
    category: "Extended",
  },
  {
    name: "Esc",
    tooltip: "Escape",
    keycode: Keycode.KC_ESCAPE,
    webCodes: ["Escape"],
    category: "Extended",
  },
  {
    name: "Bksp",
    tooltip: "Backspace",
    keycode: Keycode.KC_BACKSPACE,
    webCodes: ["Backspace"],
    category: "Extended",
  },
  {
    name: "Tab",
    keycode: Keycode.KC_TAB,
    webCodes: ["Tab"],
    category: "Extended",
  },
  {
    name: "Space",
    keycode: Keycode.KC_SPACE,
    webCodes: ["Space"],
    category: "Extended",
  },
  {
    name: "Caps",
    tooltip: "Caps Lock",
    keycode: Keycode.KC_CAPS_LOCK,
    webCodes: ["CapsLock"],
    category: "Extended",
  },
  {
    name: "F1",
    keycode: Keycode.KC_F1,
    webCodes: ["F1"],
    category: "Extended",
  },
  {
    name: "F2",
    keycode: Keycode.KC_F2,
    webCodes: ["F2"],
    category: "Extended",
  },
  {
    name: "F3",
    keycode: Keycode.KC_F3,
    webCodes: ["F3"],
    category: "Extended",
  },
  {
    name: "F4",
    keycode: Keycode.KC_F4,
    webCodes: ["F4"],
    category: "Extended",
  },
  {
    name: "F5",
    keycode: Keycode.KC_F5,
    webCodes: ["F5"],
    category: "Extended",
  },
  {
    name: "F6",
    keycode: Keycode.KC_F6,
    webCodes: ["F6"],
    category: "Extended",
  },
  {
    name: "F7",
    keycode: Keycode.KC_F7,
    webCodes: ["F7"],
    category: "Extended",
  },
  {
    name: "F8",
    keycode: Keycode.KC_F8,
    webCodes: ["F8"],
    category: "Extended",
  },
  {
    name: "F9",
    keycode: Keycode.KC_F9,
    webCodes: ["F9"],
    category: "Extended",
  },
  {
    name: "F10",
    keycode: Keycode.KC_F10,
    webCodes: ["F10"],
    category: "Extended",
  },
  {
    name: "F11",
    keycode: Keycode.KC_F11,
    webCodes: ["F11"],
    category: "Extended",
  },
  {
    name: "F12",
    keycode: Keycode.KC_F12,
    webCodes: ["F12"],
    category: "Extended",
  },
  {
    name: "PrtSc",
    tooltip: "Print Screen",
    keycode: Keycode.KC_PRINT_SCREEN,
    webCodes: ["PrintScreen"],
    category: "Extended",
  },
  {
    name: "ScrLk",
    tooltip: "Scroll Lock",
    keycode: Keycode.KC_SCROLL_LOCK,
    webCodes: ["ScrollLock"],
    category: "Extended",
  },
  {
    name: "Pause",
    keycode: Keycode.KC_PAUSE,
    webCodes: ["Pause"],
    category: "Extended",
  },
  {
    name: "Ins",
    tooltip: "Insert",
    keycode: Keycode.KC_INSERT,
    webCodes: ["Insert"],
    category: "Extended",
  },
  {
    name: "Home",
    keycode: Keycode.KC_HOME,
    webCodes: ["Home"],
    category: "Extended",
  },
  {
    name: "PgUp",
    tooltip: "Page Up",
    keycode: Keycode.KC_PAGE_UP,
    webCodes: ["PageUp"],
    category: "Extended",
  },
  {
    name: "Del",
    tooltip: "Delete",
    keycode: Keycode.KC_DELETE,
    webCodes: ["Delete"],
    category: "Extended",
  },
  {
    name: "End",
    keycode: Keycode.KC_END,
    webCodes: ["End"],
    category: "Extended",
  },
  {
    name: "PgDn",
    tooltip: "Page Down",
    keycode: Keycode.KC_PAGE_DOWN,
    webCodes: ["PageDown"],
    category: "Extended",
  },
  {
    name: "Right Arrow",
    tooltip: "Right Arrow",
    display: [ArrowRightIcon],
    keycode: Keycode.KC_RIGHT,
    webCodes: ["ArrowRight"],
    category: "Extended",
  },
  {
    name: "Left Arrow",
    tooltip: "Left Arrow",
    display: [ArrowLeftIcon],
    keycode: Keycode.KC_LEFT,
    webCodes: ["ArrowLeft"],
    category: "Extended",
  },
  {
    name: "Down Arrow",
    tooltip: "Down Arrow",
    display: [ArrowDownIcon],
    keycode: Keycode.KC_DOWN,
    webCodes: ["ArrowDown"],
    category: "Extended",
  },
  {
    name: "Up Arrow",
    tooltip: "Up Arrow",
    display: [ArrowUpIcon],
    keycode: Keycode.KC_UP,
    webCodes: ["ArrowUp"],
    category: "Extended",
  },
  {
    name: "Num\nLock",
    keycode: Keycode.KC_NUM_LOCK,
    webCodes: ["NumLock"],
    category: "Extended",
  },
  {
    name: "Num\n/",
    tooltip: "Numpad Divide",
    keycode: Keycode.KC_KP_SLASH,
    webCodes: ["NumpadDivide"],
    category: "Extended",
  },
  {
    name: "Num\n*",
    tooltip: "Numpad Multiply",
    keycode: Keycode.KC_KP_ASTERISK,
    webCodes: ["NumpadMultiply"],
    category: "Extended",
  },
  {
    name: "Num\n-",
    tooltip: "Numpad Subtract",
    keycode: Keycode.KC_KP_MINUS,
    webCodes: ["NumpadSubtract"],
    category: "Extended",
  },
  {
    name: "Num\n+",
    tooltip: "Numpad Add",
    keycode: Keycode.KC_KP_PLUS,
    webCodes: ["NumpadAdd"],
    category: "Extended",
  },
  {
    name: "Num\nEnter",
    tooltip: "Numpad Enter",
    keycode: Keycode.KC_KP_ENTER,
    webCodes: ["NumpadEnter"],
    category: "Extended",
  },
  {
    name: "Num\n1",
    tooltip: "Numpad 1 & End",
    keycode: Keycode.KC_KP_1,
    webCodes: ["Numpad1"],
    category: "Extended",
  },
  {
    name: "Num\n2",
    tooltip: "Numpad 2 & Down",
    keycode: Keycode.KC_KP_2,
    webCodes: ["Numpad2"],
    category: "Extended",
  },
  {
    name: "Num\n3",
    tooltip: "Numpad 3 & Page Down",
    keycode: Keycode.KC_KP_3,
    webCodes: ["Numpad3"],
    category: "Extended",
  },
  {
    name: "Num\n4",
    tooltip: "Numpad 4 & Left",
    keycode: Keycode.KC_KP_4,
    webCodes: ["Numpad4"],
    category: "Extended",
  },
  {
    name: "Num\n5",
    tooltip: "Numpad 5",
    keycode: Keycode.KC_KP_5,
    webCodes: ["Numpad5"],
    category: "Extended",
  },
  {
    name: "Num\n6",
    tooltip: "Numpad 6 & Right",
    keycode: Keycode.KC_KP_6,
    webCodes: ["Numpad6"],
    category: "Extended",
  },
  {
    name: "Num\n7",
    tooltip: "Numpad 7 & Home",
    keycode: Keycode.KC_KP_7,
    webCodes: ["Numpad7"],
    category: "Extended",
  },
  {
    name: "Num\n8",
    tooltip: "Numpad 8 & Up",
    keycode: Keycode.KC_KP_8,
    webCodes: ["Numpad8"],
    category: "Extended",
  },
  {
    name: "Num\n9",
    tooltip: "Numpad 9 & Page Up",
    keycode: Keycode.KC_KP_9,
    webCodes: ["Numpad9"],
    category: "Extended",
  },
  {
    name: "Num\n0",
    tooltip: "Numpad 0 & Insert",
    keycode: Keycode.KC_KP_0,
    webCodes: ["Numpad0"],
    category: "Extended",
  },
  {
    name: "Num\n.",
    tooltip: "Numpad Decimal",
    keycode: Keycode.KC_KP_DOT,
    webCodes: ["NumpadDecimal"],
    category: "Extended",
  },
  {
    name: "Menu",
    keycode: Keycode.KC_APPLICATION,
    webCodes: ["ContextMenu"],
    category: "Extended",
  },
  {
    name: "F13",
    keycode: Keycode.KC_F13,
    webCodes: ["F13"],
    category: "Extended",
  },
  {
    name: "F14",
    keycode: Keycode.KC_F14,
    webCodes: ["F14"],
    category: "Extended",
  },
  {
    name: "F15",
    keycode: Keycode.KC_F15,
    webCodes: ["F15"],
    category: "Extended",
  },
  {
    name: "F16",
    keycode: Keycode.KC_F16,
    webCodes: ["F16"],
    category: "Extended",
  },
  {
    name: "F17",
    keycode: Keycode.KC_F17,
    webCodes: ["F17"],
    category: "Extended",
  },
  {
    name: "F18",
    keycode: Keycode.KC_F18,
    webCodes: ["F18"],
    category: "Extended",
  },
  {
    name: "F19",
    keycode: Keycode.KC_F19,
    webCodes: ["F19"],
    category: "Extended",
  },
  {
    name: "F20",
    keycode: Keycode.KC_F20,
    webCodes: ["F20"],
    category: "Extended",
  },
  {
    name: "F21",
    keycode: Keycode.KC_F21,
    webCodes: ["F21"],
    category: "Extended",
  },
  {
    name: "F22",
    keycode: Keycode.KC_F22,
    webCodes: ["F22"],
    category: "Extended",
  },
  {
    name: "F23",
    keycode: Keycode.KC_F23,
    webCodes: ["F23"],
    category: "Extended",
  },
  {
    name: "F24",
    keycode: Keycode.KC_F24,
    webCodes: ["F24"],
    category: "Extended",
  },
  {
    name: "ろ",
    tooltip: "Ro (Int1)",
    keycode: Keycode.KC_INTERNATIONAL_1,
    webCodes: ["IntlRo"],
    category: "Extended",
  },
  {
    name: "かな",
    tooltip: "Katakana/Hiragana/Romaji (Int2)",
    keycode: Keycode.KC_INTERNATIONAL_2,
    webCodes: ["KanaMode"],
    category: "Extended",
  },
  {
    name: "¥",
    tooltip: "Yen (Int3)",
    keycode: Keycode.KC_INTERNATIONAL_3,
    webCodes: ["IntlYen"],
    category: "Extended",
  },
  {
    name: "変換",
    tooltip: "Henkan/Conversion (Int4)",
    keycode: Keycode.KC_INTERNATIONAL_4,
    webCodes: ["Convert"],
    category: "Extended",
  },
  {
    name: "無変換",
    tooltip: "Muhenkan/Non-Conversion (Int5)",
    keycode: Keycode.KC_INTERNATIONAL_5,
    webCodes: ["NonConvert"],
    category: "Extended",
  },
  {
    name: "Int 6",
    tooltip: "International 6 (Int6)",
    keycode: Keycode.KC_INTERNATIONAL_6,
    webCodes: [],
    category: "Extended",
  },
  {
    name: "Ime\nOn",
    tooltip: "Ime On (Lang1)",
    keycode: Keycode.KC_LANGUAGE_1,
    webCodes: ["Lang1"],
    category: "Extended",
  },
  {
    name: "Ime\nOff",
    tooltip: "Ime Off (Lang2)",
    keycode: Keycode.KC_LANGUAGE_2,
    webCodes: ["Lang2"],
    category: "Extended",
  },
  {
    name: "한/영",
    tooltip: "Hangul/English (Lang3)",
    keycode: Keycode.KC_LANGUAGE_3,
    webCodes: ["Lang3"],
    category: "Extended",
  },
  {
    name: "한자",
    tooltip: "Hanja (Lang4)",
    keycode: Keycode.KC_LANGUAGE_4,
    webCodes: ["Lang4"],
    category: "Extended",
  },
  {
    name: "Lang 5",
    tooltip: "Language 5 (Lang5)",
    keycode: Keycode.KC_LANGUAGE_5,
    webCodes: ["Lang5"],
    category: "Extended",
  },
  {
    name: "L-Ctrl",
    tooltip: "Left Control",
    keycode: Keycode.KC_LEFT_CTRL,
    webCodes: ["ControlLeft"],
    category: "Extended",
  },
  {
    name: "L-Shift",
    tooltip: "Left Shift",
    keycode: Keycode.KC_LEFT_SHIFT,
    webCodes: ["ShiftLeft"],
    category: "Extended",
  },
  {
    name: "L-Alt",
    tooltip: "Left Alt/Option",
    keycode: Keycode.KC_LEFT_ALT,
    webCodes: ["AltLeft"],
    category: "Extended",
  },
  {
    name: "L-Win",
    tooltip: "Left Windows/Super/Command",
    keycode: Keycode.KC_LEFT_GUI,
    webCodes: ["MetaLeft"],
    category: "Extended",
  },
  {
    name: "R-Ctrl",
    tooltip: "Right Control",
    keycode: Keycode.KC_RIGHT_CTRL,
    webCodes: ["ControlRight"],
    category: "Extended",
  },
  {
    name: "R-Shift",
    tooltip: "Right Shift",
    keycode: Keycode.KC_RIGHT_SHIFT,
    webCodes: ["ShiftRight"],
    category: "Extended",
  },
  {
    name: "R-Alt",
    tooltip: "Right Alt/Option",
    keycode: Keycode.KC_RIGHT_ALT,
    webCodes: ["AltRight"],
    category: "Extended",
  },
  {
    name: "R-Win",
    tooltip: "Right Windows/Super/Command",
    keycode: Keycode.KC_RIGHT_GUI,
    webCodes: ["MetaRight"],
    category: "Extended",
  },
]
